include_models:
    - name: water
    - name: beer
    - name: chicken_noodles
    - name: chewing_gum
    - name: coffee
    - name: cola
    - name: crackers
    - name: cup
    - name: deodorant
    - name: energy_drink
    - name: fanta
    - name: frutas
    - name: milk
    - name: orange_juice
    - name: pills
    - name: remia
    - name: seven_up
    - name: shaving_foam
    - name: tea
    - name: vegetable_soup
    - name: water
    - name: yoghurt
